openapi: 3.0.3
info:
  title: Ailine Reservations Management API
  description: Ailine Reservations Management API
  version: 1.0.0
servers:
  - url: 'https://api.exemple.com/v1'
    description: Production server
paths:
  /reservations/{reservation_id}:
    put:
      summary: Book or re-book a reservation
      responses:
        '200': # успешный ответ
          description: Successfull Reservation
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation_id:
                    type: string
                    description: some additional description
        '404':
          description: seat(s) unavailable. Booking failed.
          content:
            application/json:
              schema:
                type: string
                description: detailed information
      description: |
        Example request:
                   ```
                   PUT https://api.exemple.com/v1/reservations/d2725fc5-0fee
                   ```
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Unique identifier of the reservation being created or changed
          schema:
            type: string
          example: d2725fc5-0fee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                outbound:
                  type: object
                  properties:
                    flight_num:
                      type: string
                      example: "AA 253"
                    flight_date:
                      type: string
                      example: "2023-12-25T08:01:00"
                    seats:
                      type: array
                      items:
                        type: string
                returning:
                  type: object
                  properties:
                    flight_num:
                      type: string
                      example: "AA 254"
                    flight_date:
                      type: string
                      example: "2023-12-25T08:01:00"
                    seats:
                      type: array
                      items:
                        type: string
                        example: [
                          {
                            outbound: {
                              flight_num: "AA 253",
                              flight_date: "2023-12-25T08:01:00",
                              seats: [
                                "9C"
                              ]
                            },
                            returning: {
                              flight_num: "AA 254",
                              flight_date: "2023-12-28T08:01:00",
                              seats: [
                                "1C"
                              ]
                            }
                          }
                        ]
  
